### ISSUE TITLE
tailwindcss error

### ISSUE THREAD

**Issue by jayjuu1** [notpoiu/LoveLetterEffect#6]
hey, ive come across your comment on tiktok and wanted to try ur code. when I tried running it, theres an error saying
<-- 
cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation.
warn - As of Tailwind CSS v3.3, the `@tailwindcss/line-clamp` plugin is now included by default.
warn - Remove it from the `plugins` array in your configuration to eliminate this warning.
-->
how to fix this?

**Comment by notpoiu** [comment]
don't worry about tailwind giving that error, its not really that concerning as the love letter is will never reach production scale use.
